### ISSUE TITLE
 Levenshtein similarity

### ISSUE THREAD

**Issue by githubXin123** [molML/MoleculeACE#10]
https://github.com/molML/MoleculeACE/blob/024ef21d4e6e266037779cc1b133f4b210fb0464/MoleculeACE/benchmark/cliffs.py#L120
The code used to calculate the Levenshtein similarity appears to be problematic, it should be: 
`                m[i, j] = 1- (levenshtein(smiles[i], smiles[j]) / max(len(smiles[i]), len(smiles[j])))`

**Comment by derekvantilborg** [comment]
On line 127 we change the distance to a similarity: 
`m = 1 - m`
